const types = {
    FETCHING_QUESTIONS: 'FETCHING_QUESTIONS',
    QUESTIONS_FETCHED: 'QUESTIONS_FETCHED',
    QUESTIONS_FETCH_FAILED: 'QUESTIONS_FETCH_FAILED',
    BONUS_QUESTION_FETCHED: 'BONUS_QUESTION_FETCHED'
}

export default types